/* Shared Roll face engine: animates frame sequences (loop/pingpong/once/hold)
   from ROLL_ANIM, typewriters her line, then settles to idle. Each new message
   clears the last. Used by the in-app dock and the pop-out window. */
(function () {
  const ANIM = window.ROLL_ANIM;
  const NAMES = window.ROLL_EXPRESSIONS;
  const BLINK = window.ROLL_BLINK || { eyes: [] };
  const MOUTH = window.ROLL_MOUTH || { closed: 'talk_blink1', mid: 'talk_blink2', open: 'talk_blink3' };
  const IDLE_FRAME = (ANIM.idle && ANIM.idle.frames[0]) || 'talk_blink1';
  // Only genuinely big emotions play a full face animation (and skip lip-sync). Everything else —
  // happy, neutral, worried, sad, etc. — just uses the talking pipeline so she looks like she's
  // actually speaking the words, then settles to rest.
  const STRONG_EMOTION = { laugh: 1, cry: 1, shocked: 1, surprised: 1, angry: 1, rage: 1 };
  // An inline emote span ([happy]nice[/happy]) is often only a word or two, which types in ~100ms —
  // too short for the face to register. Hold the emote face at least this long before returning to
  // the neutral talking mouth, so even a subtle one-word emote is actually seen.
  const MIN_EMOTE_MS = 650;
  const now = () => (typeof performance !== 'undefined' ? performance.now() : 0);

  // --- Japanese "animalese": one short recorded clip per mora (kana syllable), played as she types
  // when her language is JP — like Animal Crossing, but with real CV sounds so you can half make it
  // out. Generated by tools/gen_mora.py (macOS `say` Kyoko, pitched up). Latin/kanji/unknown chars
  // fall back to the synth blip. A light sentence-level pitch downdrift (driftRate) keeps it from
  // sounding flat — it's cosmetic intonation, NOT real Japanese pitch accent (that needs a full
  // morphological analyzer + accent dictionary; out of scope for the sample-bank approach).
  const KANA1 = {
    'あ': 'a', 'い': 'i', 'う': 'u', 'え': 'e', 'お': 'o',
    'か': 'ka', 'き': 'ki', 'く': 'ku', 'け': 'ke', 'こ': 'ko',
    'さ': 'sa', 'し': 'shi', 'す': 'su', 'せ': 'se', 'そ': 'so',
    'た': 'ta', 'ち': 'chi', 'つ': 'tsu', 'て': 'te', 'と': 'to',
    'な': 'na', 'に': 'ni', 'ぬ': 'nu', 'ね': 'ne', 'の': 'no',
    'は': 'ha', 'ひ': 'hi', 'ふ': 'fu', 'へ': 'he', 'ほ': 'ho',
    'ま': 'ma', 'み': 'mi', 'む': 'mu', 'め': 'me', 'も': 'mo',
    'や': 'ya', 'ゆ': 'yu', 'よ': 'yo',
    'ら': 'ra', 'り': 'ri', 'る': 'ru', 'れ': 're', 'ろ': 'ro',
    'わ': 'wa', 'を': 'wo', 'ん': 'n',
    'が': 'ga', 'ぎ': 'gi', 'ぐ': 'gu', 'げ': 'ge', 'ご': 'go',
    'ざ': 'za', 'じ': 'ji', 'ず': 'zu', 'ぜ': 'ze', 'ぞ': 'zo',
    'だ': 'da', 'ぢ': 'ji', 'づ': 'zu', 'で': 'de', 'ど': 'do',
    'ば': 'ba', 'び': 'bi', 'ぶ': 'bu', 'べ': 'be', 'ぼ': 'bo',
    'ぱ': 'pa', 'ぴ': 'pi', 'ぷ': 'pu', 'ぺ': 'pe', 'ぽ': 'po',
  };
  const KANA2 = {              // yōon: a base kana + a small ゃ/ゅ/ょ collapse into one mora
    'きゃ': 'kya', 'きゅ': 'kyu', 'きょ': 'kyo', 'しゃ': 'sha', 'しゅ': 'shu', 'しょ': 'sho',
    'ちゃ': 'cha', 'ちゅ': 'chu', 'ちょ': 'cho', 'にゃ': 'nya', 'にゅ': 'nyu', 'にょ': 'nyo',
    'ひゃ': 'hya', 'ひゅ': 'hyu', 'ひょ': 'hyo', 'みゃ': 'mya', 'みゅ': 'myu', 'みょ': 'myo',
    'りゃ': 'rya', 'りゅ': 'ryu', 'りょ': 'ryo', 'ぎゃ': 'gya', 'ぎゅ': 'gyu', 'ぎょ': 'gyo',
    'じゃ': 'ja', 'じゅ': 'ju', 'じょ': 'jo', 'びゃ': 'bya', 'びゅ': 'byu', 'びょ': 'byo',
    'ぴゃ': 'pya', 'ぴゅ': 'pyu', 'ぴょ': 'pyo',
  };
  const MORA_KEYS = Array.from(new Set([...Object.values(KANA1), ...Object.values(KANA2)]));
  const KEYSET = new Set(MORA_KEYS);
  const SMALL_Y = 'ゃゅょ';
  const VIDX = { a: 0, u: 1, o: 2, i: 3, e: 4 };   // vowel -> column in a yōon row [a,u,o,i,e]
  const inSet = (k) => KEYSET.has(k);
  // Pick a yōon row member by vowel, falling back to a provided default then the row's -u member.
  const pickRow = (row, v, def) => { const k = row[VIDX[v]]; return inSet(k) ? k : (inSet(def) ? def : null); };

  // --- Animal Crossing reaction sounds (assets/roll/sfx/*.mp3). She fires one when she enters an
  // emotion span (so her [happy]…[/happy] tags also *sound*), or explicitly via [sfx=name]. They share
  // the master voice on/off but have their own volume (rollSfxVol). ---
  const SFX_SET = new Set(['amazed', 'bashfulness', 'bewilderment', 'cold-chill', 'confident',
    'curiosity', 'daydreaming', 'delight', 'distress', 'exclamation', 'fearful', 'glee', 'greetings',
    'heartbreak', 'inspiration', 'intense', 'laughter', 'love', 'mischief', 'mistaken', 'pleased',
    'pride', 'resignation', 'sheepishness', 'shocked', 'showmanship', 'sighing', 'sleepy', 'sneezing',
    'worry']);
  // Her expression names -> the AC reaction that fits, so the emotion tags she already uses play a sound.
  const EMOTE_SFX = {
    happy: 'delight', laugh: 'laughter', surprised: 'amazed', shocked: 'shocked', worried: 'worry',
    sad: 'heartbreak', cry: 'distress', angry: 'intense', rage: 'intense', wink: 'mischief',
    blush: 'bashfulness', shame: 'sheepishness', whine: 'distress',
  };
  // Katakana -> hiragana (same 0x60 offset block) so one table voices both scripts.
  const toHira = (ch) => { const c = ch.charCodeAt(0); return (c >= 0x30A1 && c <= 0x30F6) ? String.fromCharCode(c - 0x60) : ch; };
  const vowelOf = (key) => { const v = key[key.length - 1]; return 'aiueo'.includes(v) ? v : ''; };
  const isSentenceEnd = (ch) => '。．.!?！？'.includes(ch);

  // Parse Roll's BBCode-ish markup into one attribute object per visible character. Tags:
  //   emotion: [happy]…[/happy] (any expression name) → emote that face DURING the span, lip-sync
  //            outside it. style: [b] [i] [c=orange] [shake] [wave]. pacing: [slow]/[fast] spans,
  //            [.] or [p] = a held pause before the next character. Unknown tags are ignored.
  // The result is index-aligned with the plain text, so word-wrap (which only swaps a space for a
  // newline) keeps the attributes lined up with the rendered characters.
  function parseMarkup(text) {
    const chars = [];
    const stack = [];
    let pause = 0;
    const attrFor = () => {
      const a = { emote: null, b: false, i: false, color: null, shake: false, wave: false, speed: 1 };
      for (const t of stack) {
        if (NAMES.includes(t.name)) a.emote = t.name;
        else if (t.name === 'b') a.b = true;
        else if (t.name === 'i') a.i = true;
        else if (t.name === 'c') a.color = t.val || a.color;
        else if (t.name === 'shake') a.shake = true;
        else if (t.name === 'wave') a.wave = true;
        else if (t.name === 'slow') a.speed = 0.5;
        else if (t.name === 'fast') a.speed = 2;
      }
      return a;
    };
    let pendingSfx = null, pendingSfxRate = 1;     // a [sfx=…] fires on the next typed character
    const emit = (s) => {
      for (const ch of s) {
        const a = attrFor(); a.ch = ch;
        a.pause = pause; pause = 0;
        a.sfx = pendingSfx; a.sfxRate = pendingSfxRate; pendingSfx = null;   // attach to the first char only
        chars.push(a);
      }
    };
    const re = /\[(\/?)([a-z.]+)(?:=([^\]]+))?\]/gi;
    let last = 0, m;
    while ((m = re.exec(text))) {
      emit(text.slice(last, m.index));
      last = re.lastIndex;
      const name = m[2].toLowerCase();
      if (name === '.' || name === 'p') { pause += 350; continue; }
      if (name === 'pause') { pause += m[3] ? Math.max(0, Math.min(8000, parseInt(m[3], 10) || 350)) : 350; continue; }
      if (name === 'sfx') {                          // [sfx=love] or [sfx=laughter:1.4] (a reaction at a speed)
        const [k, r] = String(m[3] || '').split(':');
        pendingSfx = (k || '').trim().toLowerCase() || null;
        pendingSfxRate = r ? Math.max(0.5, Math.min(2.5, parseFloat(r) || 1)) : 1;
        continue;
      }
      if (m[1] === '/') { for (let k = stack.length - 1; k >= 0; k--) if (stack[k].name === name) { stack.splice(k, 1); break; } }
      else stack.push({ name, val: m[3] });
    }
    emit(text.slice(last));
    return chars;
  }
  const stripMarkup = (text) => parseMarkup(String(text)).map((c) => c.ch).join('');

  // Roll's downloaded voice clips: name → file under assets/roll/voice. Chosen by MEANING
  // (pickClip, in the renderer), the same way an expression is chosen, and played as she starts
  // a line. Names are the Japanese she actually says.
  const CLIPS = {
    appear:   'ro_appear',              // entrance / power-on
    ikuyo:    'ro_toujou_ikuyo',        // 行くよ — here we go (new / changed task)
    mitete:   'ro_toujou_mitete',       // 見てて — watch this (a discovery)
    yattane:  'ro_syoupo-zu_yattane',   // やったね — we did it (success)
    tasukete: 'ro_nakamayobi_tasukete', // 助けて — help (error / needs you)
    makasete: 'ro_koutaitou_makasete',  // 任せて — leave it to me
    sore:     'ro_kiai_soreltu',        // それっ — there! (effort)
    ya:       'ro_kiai_yaltu',          // やっ — hyah! (effort)
    kya:      'ro_ko_kya-ltu',          // きゃっ — eek! (surprise)
  };

  // Shared across every RollFace in this renderer so the one-time mic unlock can never
  // be requested twice concurrently (no stacked macOS prompts).
  let unlockPromise = null;

  class RollFace {
    constructor(faceEl, msgEl, opts) {
      this.faceEl = faceEl;
      this.msgEl = msgEl;
      this.base = (opts && opts.base) || '../assets/'; // app: src/ → ../assets; the landing page overrides
      // Two stacked layers: mouth/base (this.img) + eyes overlay (this.eyes, clipped to the top
      // 20px in CSS) so blinking and the mouth animate independently.
      this.img = document.createElement('img');
      this.img.alt = 'Roll';
      this.eyes = document.createElement('img');
      this.eyes.className = 'eyes';
      this.eyes.alt = '';
      this.eyes.setAttribute('aria-hidden', 'true');
      this.faceEl.replaceChildren(this.img, this.eyes);
      // Preload the blink eye-frames so the first blink doesn't show a blank/late swap while the
      // PNG fetches — the browser keeps them cached for the overlay.
      for (const f of (BLINK.eyes || [])) { const im = new Image(); im.src = `${this.base}roll/frames/${f}.png`; }
      this.talking = false;
      this.animTimer = null;
      this.blinkAnim = null;
      this.typeTimer = null;
      this.settleTimer = null;
      this.queue = [];                       // lines waiting their turn (never interrupts the current one)
      this._clipBytes = {};                  // name -> fetched ArrayBuffer
      this._clipBufs = new Map();            // name -> Map(ctx -> decoded AudioBuffer)
      this._lastClipAt = 0;
      this._moraBytes = {};                  // mora key -> ArrayBuffer (per-syllable voice)
      this._moraBufs = new Map();            // mora key -> Map(ctx -> AudioBuffer)
      this._moraNode = new Map();            // ctx -> last {src, gain}, so a new mora can duck the prior
      this._moraPreloaded = false;
      this._sfxBytes = {};                   // sfx key -> ArrayBuffer (AC reaction sounds)
      this._sfxBufs = new Map();             // sfx key -> Map(ctx -> AudioBuffer)
      this._lastSfxAt = 0;
      this._voiceSkip = 0;                   // how many upcoming chars a multi-char mora already voiced
      this._moraPos = 0;                     // mora index within the phrase, for the cosmetic downdrift
      this._lastVowel = '';                  // last mora's vowel, so a long-vowel mark ー can extend it
      this.play('idle');
      this._initAudio();
    }

    _frame(f) { this.img.src = `${this.base}roll/frames/${f}.png`; }
    _eyeFrame(f) { this.eyes.src = `${this.base}roll/frames/${f}.png`; }

    // The CRT shader paints a WebGL canvas OVER her face rect, so it can only show what it samples —
    // and it samples this ONE source. The base <img> alone drops the blink (the .eyes overlay is a
    // separate DOM layer the canvas covers). So composite base + eyes here, mirroring the CSS clip on
    // .eyes (top 62.5% = the eye band), so blinks survive with the shader on. Returns a 32x32 canvas.
    faceSource() {
      const base = this.img;
      if (!base || !base.complete || !base.naturalWidth) return null;
      const w = base.naturalWidth, hN = base.naturalHeight;
      let c = this._composite;
      if (!c) { c = this._composite = document.createElement('canvas'); }
      if (c.width !== w || c.height !== hN) { c.width = w; c.height = hN; }
      const g = this._compositeCtx || (this._compositeCtx = c.getContext('2d'));
      g.imageSmoothingEnabled = false;
      g.clearRect(0, 0, w, hN);
      g.drawImage(base, 0, 0, w, hN);
      const eyes = this.eyes;
      if (eyes && eyes.style.display !== 'none' && eyes.complete && eyes.naturalWidth) {
        const cut = Math.round(hN * 0.625);   // matches .eyes clip-path: inset(0 0 37.5% 0)
        g.drawImage(eyes, 0, 0, w, cut, 0, 0, w, cut);
      }
      return c;
    }

    // Resolve which output device Roll should sing through. Default: system output only,
    // no routing — we must NEVER ask for the microphone just to read device labels, since
    // that triggers a native macOS prompt for every user. OBS users opt in explicitly by
    // setting localStorage 'rollSink' to a device-label substring (e.g. 'blackhole'); only
    // then do we do the one-time mic unlock to reveal labels and tap that DEVICE for OBS.
    //   unset / '' / 'default' → system default output (no routing, no mic prompt)
    //   <substr>               → first audiooutput whose label contains <substr> (case-insensitive)
    // The chosen deviceId is cached in 'rollSinkId'; the mic unlock happens AT MOST ONCE EVER
    // (gated by 'rollMicTried' across launches + a shared in-flight promise across windows).
    async _resolveSinkId() {
      let pref = null;
      try { pref = localStorage.getItem('rollSink'); } catch (_) {}
      if (!pref || !pref.trim() || pref === 'default') return null; // opt-in only — no mic by default
      const match = pref.trim().toLowerCase();
      try { const c = localStorage.getItem('rollSinkId'); if (c) return c; } catch (_) {}
      const md = navigator.mediaDevices;
      if (!md || !md.enumerateDevices) return null;
      const find = (list) => list.find((d) => d.kind === 'audiooutput' && (d.label || '').toLowerCase().includes(match));
      let dev = find(await md.enumerateDevices());
      // Labels stay hidden until a media device is unlocked once. Try that a single time —
      // ever — then stop, so a denied/dismissed prompt doesn't nag on every launch.
      if (!dev) {
        let tried = false;
        try { tried = localStorage.getItem('rollMicTried') === '1'; } catch (_) {}
        if (!tried) {
          try { localStorage.setItem('rollMicTried', '1'); } catch (_) {} // set BEFORE asking
          unlockPromise = unlockPromise || md.getUserMedia({ audio: true })
            .then((s) => { s.getTracks().forEach((t) => t.stop()); })
            .catch(() => { /* mic blocked — fall back to default output */ });
          await unlockPromise;
          dev = find(await md.enumerateDevices());
        }
      }
      if (dev && dev.deviceId) {
        try { localStorage.setItem('rollSinkId', dev.deviceId); } catch (_) {}
        return dev.deviceId;
      }
      return null;
    }

    // Roll speaks through TWO output contexts at once:
    //   _audio — the system default output, NEVER routed, so YOU always hear her.
    //   _cap   — a best-effort second context pinned to the capture device (BlackHole)
    //            so OBS can tap her voice off that DEVICE. Purely additive: if the sink
    //            can't be resolved (mic denied, no BlackHole, no setSinkId support), Roll
    //            still plays on _audio. We never mute the default output to feed OBS.
    _initAudio() {
      const Ctor = window.AudioContext || window.webkitAudioContext;
      if (!Ctor) return;
      try { this._audio = new Ctor(); } catch (_) { return; /* audio unavailable */ }
      if (typeof this._audio.setSinkId !== 'function') return; // no per-context routing here
      this._resolveSinkId()
        .then((id) => {
          if (!id) return; // 'default' pref, or no capture device — default output is enough
          const cap = new Ctor();
          return cap.setSinkId(id).then(() => {
            this._cap = cap;
            console.log('[Roll] OBS tap → sink', id);
          });
        })
        .catch(() => { /* capture routing unavailable — default output only */ });
    }

    // Animal-Crossing-style "animalese" blip per character, fanned to every active
    // context (default + optional capture) so it's audible AND captured.
    _blip(ch) {
      try {
        if (localStorage.getItem('rollVoice') === 'off') return;
      } catch (_) {}
      const lc = ch.toLowerCase();
      const code = (lc.charCodeAt(0) || 100);
      // higher, feminine register; pitch wanders with the letter = "speech"
      const freq = 520 + (code % 22) * 22;
      const isCons = lc >= 'a' && lc <= 'z' && 'aeiou'.indexOf(lc) === -1; // consonants get a vibrato wobble
      for (const ctx of [this._audio, this._cap]) {
        if (ctx) { try { this._tone(ctx, freq, isCons); } catch (_) { /* this sink blocked — skip */ } }
      }
    }

    _langJa() { try { return localStorage.getItem('rollLang') === 'ja'; } catch (_) { return false; } }
    _voiceOff() { try { return localStorage.getItem('rollVoice') === 'off'; } catch (_) { return false; } }
    // Voice style: 'mora' = spoken syllables (kana + English read as katakana), 'blips' = synth.
    // Unset defaults to spoken for Japanese, blips for English — the toggle overrides either way.
    _moraOn() {
      let s = null; try { s = localStorage.getItem('rollVoiceStyle'); } catch (_) {}
      if (s === 'mora') return true;
      if (s === 'blips') return false;
      return this._langJa();
    }

    // Warm the whole mora bank into the default context once, so the first JP line doesn't gap while
    // each clip fetches. ~100 tiny files; the capture context (if any) decodes lazily on first play.
    _ensureMoraPreload() {
      if (this._moraPreloaded) return;
      const ctx = this._audio;
      if (!ctx) return;                       // audio not up yet — try again on the next line
      this._moraPreloaded = true;
      for (const key of MORA_KEYS) {
        fetch(`${this.base}roll/mora/${key}.wav`)
          .then((r) => r.arrayBuffer())
          .then((b) => { this._moraBytes[key] = b; return ctx.decodeAudioData(b.slice(0)); })
          .then((buf) => { let m = this._moraBufs.get(key); if (!m) { m = new Map(); this._moraBufs.set(key, m); } m.set(ctx, buf); })
          .catch(() => { /* missing clip → that mora just falls back to a synth blip */ });
      }
    }

    // Per-clip playback rate. Three ingredients: (1) a cosmetic phrase downdrift — start a touch high,
    // drift down, reset at sentence ends (intonation, NOT real pitch accent); (2) faster typing → faster
    // clips, so they overlap less at quick speeds; (3) a hair of jitter for life. Advances _moraPos.
    _moraRate() {
      const p = Math.min(this._moraPos, 12);
      this._moraPos += 1;
      const drift = 0.05 - p * 0.006;                       // +5% at phrase start → ~0 by the tail
      const jitter = (Math.random() - 0.5) * 0.015;
      const ms = this._baseDelay();                          // her typing speed, ms/char (14..75)
      const speed = Math.max(1.0, Math.min(1.6, 1 + (38 - ms) / 120)); // faster typing → quicker clips; never lower
      return Math.max(1.0, Math.min(2.0, speed * (1 + drift + jitter))); // floor at 1.0 so pitch stays up
    }

    // English/romaji letter(s) -> the nearest mora clip key, read as katakana-English (consonant gets an
    // epenthetic vowel: t/d -> o, else u; l->r, v->b, f->h row, c->k/s, digraphs sh/ch/th/ph/ck). Returns
    // { key, consumed } where consumed = how many FOLLOWING chars it ate (a vowel and/or a digraph tail).
    _latinMora(ch, ahead) {
      const V = 'aeiou';
      const c = ch.toLowerCase();
      if (V.includes(c)) return { key: c, consumed: 0 };     // bare vowel = its own mora (a/i/u/e/o)
      let cons = c, consumed = 0;
      const a0 = (ahead[0] || '').toLowerCase();
      if (c === 's' && a0 === 'h') { cons = 'sh'; consumed = 1; }
      else if (c === 'c' && a0 === 'h') { cons = 'ch'; consumed = 1; }
      else if (c === 't' && a0 === 'h') { cons = 's'; consumed = 1; }   // th -> s
      else if (c === 'p' && a0 === 'h') { cons = 'f'; consumed = 1; }   // ph -> f
      else if (c === 'c' && a0 === 'k') { cons = 'k'; consumed = 1; }   // ck -> k
      const nv = (ahead[consumed] || '').toLowerCase();
      if (cons === 'n' && !V.includes(nv)) return { key: 'n', consumed }; // ん before a consonant/end
      let vowel;
      if (V.includes(nv)) { vowel = nv; consumed += 1; }
      else vowel = (cons === 't' || cons === 'd') ? 'o' : 'u';          // epenthetic (build -> bi-ru-do)
      const key = this._cvKey(cons, vowel);
      return key ? { key, consumed } : null;
    }

    // Resolve a consonant+vowel to an actual clip key, applying Japanese phonotactics + bank fallbacks.
    _cvKey(cons, v) {
      if (!cons) return 'aiueo'.includes(v) ? v : null;
      if (cons === 'sh') return pickRow(['sha', 'shu', 'sho', 'shi', 'she'], v, 'shu');
      if (cons === 'ch') return pickRow(['cha', 'chu', 'cho', 'chi', 'che'], v, 'chu');
      if (cons === 'j') return pickRow(['ja', 'ju', 'jo', 'ji', 'je'], v, 'ju');
      const row = ({ l: 'r', v: 'b', q: 'k', x: 'k', f: 'h', c: (v === 'e' || v === 'i') ? 's' : 'k' })[cons] || cons;
      let key = row + v;
      const fix = { si: 'shi', ti: 'chi', tu: 'tsu', hu: 'fu', zi: 'ji', di: 'ji', du: 'zu', yi: 'i', ye: 'e', wu: 'u', wi: 'wo', we: 'wo' };
      if (fix[key]) key = fix[key];
      if (inSet(key)) return key;
      for (const fb of [row + 'u', row + 'a', v]) if (inSet(fb)) return fb;   // graceful nearest
      return null;
    }

    // Voice one typed character when "syllables" style is on. Plays the kana's mora (consuming a small
    // ゃ/ゅ/ょ for yōon, extending a long-vowel ー, gapping on a small っ); otherwise reads a Latin letter
    // as katakana-English. Returns how many FOLLOWING chars it already voiced (so the stepper skips them).
    // Anything it can't map (kanji, digits, symbols) falls back to the throttled synth blip.
    _voiceChar(ch, ahead, i) {
      if (this._voiceOff()) return 0;
      if (this._moraOn()) {
        this._ensureMoraPreload();
        if (ch === 'っ' || ch === 'ッ') return 0;                       // geminate: brief silent gap
        if (ch === 'ー' || ch === '〜' || ch === '～') { if (this._lastVowel) this._playMora(this._lastVowel); return 0; }
        const h = toHira(ch);
        const hn = ahead[0] ? toHira(ahead[0]) : '';
        if (hn && SMALL_Y.includes(hn) && KANA2[h + hn]) {              // base + small y → one mora
          const k2 = KANA2[h + hn]; this._playMora(k2); this._lastVowel = vowelOf(k2); return 1;
        }
        if (KANA1[h]) { const k1 = KANA1[h]; this._playMora(k1); this._lastVowel = vowelOf(k1); return 0; }
        if (/[a-zA-Z]/.test(ch)) {                                      // English → katakana
          const r = this._latinMora(ch, ahead);
          if (r && r.key) { this._playMora(r.key); this._lastVowel = vowelOf(r.key) || this._lastVowel; return r.consumed; }
        }
        // unmapped (kanji/symbol) → fall through to a synth blip
      }
      if (i % 2 === 0) this._blip(ch);
      return 0;
    }

    // Play a mora clip into every active context (default + optional OBS capture). Monophonic per
    // context: the previous mora is quickly ducked + stopped so fast typing doesn't pile clips into
    // mush. Fetch+decode are cached per key/context; level ties to the 'rollBlipVol' slider.
    async _playMora(key) {
      if (this._voiceOff()) return;
      const rate = this._moraRate();            // computed up front (before any await) so order holds
      const gain = Math.max(0.0002, this._blipVol() * 0.5);
      let bytes = this._moraBytes[key];
      if (!bytes) {
        try { bytes = await (await fetch(`${this.base}roll/mora/${key}.wav`)).arrayBuffer(); this._moraBytes[key] = bytes; }
        catch (_) { return; }
      }
      let bufs = this._moraBufs.get(key);
      if (!bufs) { bufs = new Map(); this._moraBufs.set(key, bufs); }
      for (const ctx of [this._audio, this._cap]) {
        if (!ctx) continue;
        try {
          if (ctx.state === 'suspended') ctx.resume();
          let buf = bufs.get(ctx);
          if (!buf) { buf = await ctx.decodeAudioData(bytes.slice(0)); bufs.set(ctx, buf); }
          const t = ctx.currentTime;
          const prev = this._moraNode.get(ctx);                 // duck the previous syllable, don't stack
          if (prev) { try { prev.gain.gain.cancelScheduledValues(t); prev.gain.gain.setTargetAtTime(0.0001, t, 0.03); prev.src.stop(t + 0.13); } catch (_) {} }
          const src = ctx.createBufferSource(); src.buffer = buf; src.playbackRate.value = rate;
          const g = ctx.createGain(); g.gain.value = gain;
          src.connect(g).connect(ctx.destination); src.start();
          this._moraNode.set(ctx, { src, gain: g });
        } catch (_) { /* this sink failed — skip it */ }
      }
    }

    // AC reaction-sound volume (own slider, like clips/blips). Stored as rollSfxVol 0..1, default 0.45.
    _sfxVol() {
      let v = 0.45;
      try { const s = localStorage.getItem('rollSfxVol'); if (s != null && s !== '') v = parseFloat(s); } catch (_) {}
      return isNaN(v) ? 0.45 : Math.max(0, Math.min(1, v));
    }

    // Play an Animal Crossing reaction sound by key (or by an emotion name, which maps to one). Optional
    // rate (e.g. [sfx=laughter:1.4]) plays it faster/slower for emphasis. Shares the master voice on/off,
    // uses its own volume, and is lightly throttled so a flurry of emote spans can't machine-gun it.
    async _playSfx(name, rate) {
      if (!name || this._voiceOff()) return;
      const key = SFX_SET.has(name) ? name : EMOTE_SFX[name];     // accept a reaction key OR an emotion
      if (!key || !SFX_SET.has(key)) return;
      const t = now();
      if (this._lastSfxAt && t - this._lastSfxAt < 320) return;   // don't stack reactions on top of each other
      this._lastSfxAt = t;
      const r = Math.max(0.5, Math.min(2.5, rate || 1));
      const gain = Math.max(0.0002, this._sfxVol() * 0.7);
      let bytes = this._sfxBytes[key];
      if (!bytes) {
        try { bytes = await (await fetch(`${this.base}roll/sfx/${key}.mp3`)).arrayBuffer(); this._sfxBytes[key] = bytes; }
        catch (_) { return; }
      }
      let bufs = this._sfxBufs.get(key);
      if (!bufs) { bufs = new Map(); this._sfxBufs.set(key, bufs); }
      for (const ctx of [this._audio, this._cap]) {
        if (!ctx) continue;
        try {
          if (ctx.state === 'suspended') ctx.resume();
          let buf = bufs.get(ctx);
          if (!buf) { buf = await ctx.decodeAudioData(bytes.slice(0)); bufs.set(ctx, buf); }
          const src = ctx.createBufferSource(); src.buffer = buf; src.playbackRate.value = r;
          const g = ctx.createGain(); g.gain.value = gain;
          src.connect(g).connect(ctx.destination); src.start();
        } catch (_) { /* this sink failed — skip it */ }
      }
    }

    // Animalese blip peak gain. User-adjustable via localStorage 'rollBlipVol' (0..1) so it can be
    // balanced against the recorded clips; default 0.55 maps to the original ~0.038 peak.
    _blipVol() {
      let v = 0.55;
      try { const s = localStorage.getItem('rollBlipVol'); if (s != null && s !== '') v = parseFloat(s); } catch (_) {}
      return isNaN(v) ? 0.55 : Math.max(0, Math.min(1, v));
    }

    // Emit one animalese "boop" at `freq` into a single AudioContext. A sine that glides down a
    // touch per letter (bubbly), consonants get a quick vibrato wobble for "speechy" texture, and
    // a subtle square wave an octave down adds retro low-end body. (Preview voice #6 + sub-bass.)
    _tone(ctx, freq, isCons) {
      if (ctx.state === 'suspended') ctx.resume();
      const t = ctx.currentTime;
      // soft lowpass for a rounded, non-buzzy tone
      const lp = ctx.createBiquadFilter();
      lp.type = 'lowpass'; lp.frequency.value = 1900; lp.Q.value = 0.5;
      const peak = Math.max(0.0002, 0.07 * this._blipVol());
      const g = ctx.createGain();
      g.gain.setValueAtTime(0.0001, t);
      g.gain.exponentialRampToValueAtTime(peak, t + 0.015); // gentle attack
      g.gain.exponentialRampToValueAtTime(0.0001, t + 0.1); // soft tail
      lp.connect(g).connect(ctx.destination);
      // main sine "boop" — glides down slightly across the note
      const o = ctx.createOscillator(); o.type = 'sine';
      o.frequency.setValueAtTime(freq * 1.15, t);
      o.frequency.exponentialRampToValueAtTime(freq * 0.9, t + 0.1);
      o.connect(lp); o.start(t); o.stop(t + 0.11);
      // subtle square sub-bass an octave down — low gain so it's felt as body, not heard as buzz
      const sub = ctx.createOscillator(); sub.type = 'square'; sub.frequency.value = freq * 0.5;
      const sg = ctx.createGain(); sg.gain.value = 0.14;
      sub.connect(sg).connect(lp); sub.start(t); sub.stop(t + 0.11);
      // consonants wobble (vibrato); vowels glide clean
      if (isCons) {
        const lfo = ctx.createOscillator(); lfo.frequency.value = 20;
        const lfoG = ctx.createGain(); lfoG.gain.value = 26;
        lfo.connect(lfoG).connect(o.detune); lfo.start(t); lfo.stop(t + 0.11);
      }
    }

    // Clip playback gain. Recorded clips are far hotter than the synthesized animalese (~0.04 peak),
    // so default low to sit alongside it; user-adjustable via localStorage 'rollClipVol' (0..1).
    _clipVol() {
      let v = 0.3;
      try { const s = localStorage.getItem('rollClipVol'); if (s != null && s !== '') v = parseFloat(s); } catch (_) {}
      return isNaN(v) ? 0.3 : Math.max(0, Math.min(1, v));
    }

    // Play a named voice clip into EVERY active context (default + optional capture) so it's both
    // audible AND captured by OBS — same routing as the animalese. Throttled + mute-aware. Buffers
    // are fetched once and decoded once per context, then reused.
    async _playClip(name) {
      try { if (localStorage.getItem('rollVoice') === 'off') return; } catch (_) {}
      const file = CLIPS[name];
      if (!file) return;
      const now = (typeof performance !== 'undefined' ? performance.now() : 0);
      if (this._lastClipAt && now - this._lastClipAt < 4500) return; // don't stack exclamations
      this._lastClipAt = now;
      let bytes = this._clipBytes[name];
      if (!bytes) {
        try { bytes = await (await fetch(`${this.base}roll/voice/${file}.wav`)).arrayBuffer(); this._clipBytes[name] = bytes; }
        catch (_) { return; }
      }
      let bufs = this._clipBufs.get(name);
      if (!bufs) { bufs = new Map(); this._clipBufs.set(name, bufs); }
      for (const ctx of [this._audio, this._cap]) {
        if (!ctx) continue;
        try {
          if (ctx.state === 'suspended') ctx.resume();
          let buf = bufs.get(ctx);
          if (!buf) { buf = await ctx.decodeAudioData(bytes.slice(0)); bufs.set(ctx, buf); }
          const src = ctx.createBufferSource(); src.buffer = buf;
          // CLIP_SCALE pulls the whole recorded-clip range down so the slider lives at a usable
          // position instead of pinned near zero — the raw .wav files are very hot. Kept low so her
          // baseline exclamations sit UNDER the animalese, not on top of it.
          const g = ctx.createGain(); g.gain.value = this._clipVol() * 0.26;
          src.connect(g).connect(ctx.destination);
          src.start();
        } catch (_) { /* this sink failed — skip it */ }
      }
    }

    // First-boot flourish: she's hidden for a beat (caller pre-adds .warp-pending), then "appears"
    // with the clip + a CRT/teleport warp-in, settles, and greets. The CSS .warp-in animates the
    // DOM <img> (seen when the shader is OFF); with the shader ON it paints over that, so we ALSO
    // drive the turn-on through the shader (Fx.powerOn) — that's the version actually visible there.
    intro(greeting) {
      const fx = window.Fx;
      if (fx && fx.setPowerOn) fx.setPowerOn(0); // keep her dark behind the shader until she fires on
      setTimeout(() => {
        this.faceEl.classList.remove('warp-pending');
        this.faceEl.classList.add('warp-in');
        if (fx && fx.powerOn) fx.powerOn(1100);  // CRT tube turn-on, matched to the .warp-in duration
        this._playClip('appear');
        this.play('idle');
        setTimeout(() => this.faceEl.classList.remove('warp-in'), 1100);
        if (greeting) setTimeout(() => this.speak(greeting), 750);
      }, 900);
    }

    play(name) {
      // mode drives blinking: 'idle' (rest/neutral) and 'talk' (neutral mouth) blink on a timer;
      // emotional expressions ('expr') have their own faces (and own eyes) so the overlay is off.
      this._mode = name === 'talk' ? 'talk' : (name === 'idle' || name === 'neutral') ? 'idle' : 'expr';
      this._runAnim(ANIM[name] || ANIM.neutral);
      if (this._mode === 'expr') { clearTimeout(this.blinkTimer); this.blinkTimer = null; this._endBlink(); }
      else this._scheduleBlink();
    }

    // Drive a single ANIM entry (loop/pingpong/once/hold). No blink/scheduler side effects, so the
    // blink overlay can pause and resume the base animation through it.
    _runAnim(a) {
      if (this.animTimer) { clearInterval(this.animTimer); this.animTimer = null; }
      let seq = a.frames.slice();
      if (a.mode === 'pingpong' && seq.length > 2) seq = seq.concat(a.frames.slice(1, -1).reverse());
      this._frame(seq[0]);
      if (a.mode === 'hold' || seq.length < 2) return;
      let i = 0;
      this.animTimer = setInterval(() => {
        i += 1;
        if (a.mode === 'once' && i >= seq.length) {
          clearInterval(this.animTimer); this.animTimer = null;
          this._frame(seq[seq.length - 1]);
          return;
        }
        this._frame(seq[i % seq.length]);
      }, 1000 / (a.fps || 4));
    }

    // --- blinking -------------------------------------------------------------
    // A randomized heartbeat: blink once (and ~1-in-5 times, twice fast). Only fires while she's at
    // rest or doing the neutral talk; any state change reschedules it. She blinks ROUGHLY TWICE AS
    // OFTEN while talking (like people do) — and on a fast enough cadence that a blink actually lands
    // during a short reply, instead of the old ~4.5s average that mostly fired between sentences.
    _scheduleBlink() {
      clearTimeout(this.blinkTimer);
      const talk = this._mode === 'talk';
      const min = talk ? 900 : 2200;
      const span = talk ? 1800 : 3800;
      this.blinkTimer = setTimeout(() => this._doBlink(), min + Math.random() * span);
    }
    _doBlink() {
      if (this._mode !== 'idle' && this._mode !== 'talk') { this._scheduleBlink(); return; }
      const dbl = Math.random() < 0.2;
      this._blinkSeq(() => {
        // double-blink: a brief eyes-open beat (~90ms), then a second blink, reads as the real thing
        if (dbl) this.dblTimer = setTimeout(() => this._blinkSeq(() => this._scheduleBlink()), 90);
        else this._scheduleBlink();
      });
    }
    // Human blink on the EYES OVERLAY only — the mouth/base layer underneath is untouched, so it
    // reads the same whether she's idle or mid-sentence. ~4 frames × 55ms ≈ 220ms, with the shut
    // frame held twice (~110ms closed) so the blink is actually perceptible, not a 35ms flash.
    _blinkSeq(done) {
      const seq = BLINK.eyes;
      if (!this.eyes || !seq || !seq.length) { done(); return; }
      if (this.blinkAnim) { clearInterval(this.blinkAnim); this.blinkAnim = null; }
      let i = 0;
      this._eyeFrame(seq[0]);               // paint the first frame BEFORE showing, so there's no
      this.eyes.style.display = 'block';    // blank flash while the (preloaded) image swaps in
      this.blinkAnim = setInterval(() => {
        i += 1;
        if (i >= seq.length) {
          clearInterval(this.blinkAnim); this.blinkAnim = null;
          this.eyes.style.display = 'none';   // reveal the base's open eyes again
          done();
          return;
        }
        this._eyeFrame(seq[i]);
      }, 55);
    }
    _endBlink() {
      if (this.blinkAnim) { clearInterval(this.blinkAnim); this.blinkAnim = null; }
      if (this.dblTimer) { clearTimeout(this.dblTimer); this.dblTimer = null; }
      if (this.eyes) this.eyes.style.display = 'none';
    }
    // One viseme per printed character so the mouth tracks the actual words: space/punctuation
    // closes it, vowels open wide (a run of vowels just holds open), consonants land mid.
    _mouthForChar(ch) {
      if (!ch || !ch.trim() || '.,!?;:…—-'.includes(ch)) { this._frame(MOUTH.closed); return; }
      this._frame('aeiouyAEIOUY'.includes(ch) ? MOUTH.open : MOUTH.mid);
    }
    // Greedy word-wrap to explicit newlines BEFORE typing, so a word never starts on one line and
    // then jumps to the next when it overflows — it begins on the line where it fits. Measured
    // against the live message box width in its own font. Over-long single words fall back to the
    // CSS break (word-break) so they can't run off the edge.
    _wrap(text) {
      const el = this.msgEl;
      const cs = getComputedStyle(el);
      const maxW = el.clientWidth - parseFloat(cs.paddingLeft || 0) - parseFloat(cs.paddingRight || 0);
      if (!maxW || maxW <= 0) return text;
      if (!this._measure) this._measure = document.createElement('canvas').getContext('2d');
      this._measure.font = `${cs.fontSize} ${cs.fontFamily}`;
      const width = (s) => this._measure.measureText(s).width;
      const out = [];
      for (const para of String(text).split('\n')) {
        let line = '';
        for (const word of para.split(' ')) {
          const trial = line ? line + ' ' + word : word;
          if (line && width(trial) > maxW) { out.push(line); line = word; }
          else line = trial;
        }
        out.push(line);
      }
      return out.join('\n');
    }

    // Baseline ms-per-character for typing, user-tunable via the ⚙ panel (localStorage 'rollTextSpeed').
    // Read fresh each line so a drag takes effect on her next reply. Defaults to 38 (the old constant).
    _baseDelay() {
      let v = 38;
      try { const s = localStorage.getItem('rollTextSpeed'); if (s != null && s !== '') v = parseFloat(s); } catch (_) {}
      return isNaN(v) ? 38 : Math.max(6, Math.min(140, v));
    }

    _clear() {
      if (this.typeTimer) { clearTimeout(this.typeTimer); this.typeTimer = null; }
      if (this.settleTimer) { clearTimeout(this.settleTimer); this.settleTimer = null; }
      if (this._emoteHoldTimer) { clearTimeout(this._emoteHoldTimer); this._emoteHoldTimer = null; }
    }

    // Public entry: never cut off a line that's mid-type. If she's talking (or lines are
    // already waiting), queue this one and let the current finish + breathe first.
    speak(state) {
      if (!state || !state.line) return;
      if (this.talking || this.queue.length) {
        if (this.queue.length >= 4) this.queue.shift(); // keep the backlog recent, not infinite
        this.queue.push(state);
        return;
      }
      this._startSpeak(state);
    }

    // Render a line INSTANTLY — full text, settled expression, no typing/queue/blips. Used for
    // window-to-window handoff (dock ⇄ pop-out) so a message already on screen isn't re-typed.
    show(state) {
      if (!state || !state.line) return;
      this._clear();
      this._stopThinking();
      this.queue.length = 0;
      this.talking = false;
      if (this.onStart) { try { this.onStart(state); } catch (_) {} }
      const expr = NAMES.includes(state.expression) ? state.expression : 'neutral';
      this.msgEl.classList.remove('typing');
      this.msgEl.textContent = stripMarkup(state.line);   // instant render: drop tags, plain text
      this.msgEl.scrollTop = this.msgEl.scrollHeight;
      this.play(expr);
    }

    // Looping "Roll is thinking…" status while her brain works — resting face + blink (NOT talking),
    // pulsing yellow-orange (CSS .thinking). Cleared the moment a real line starts.
    thinking() {
      this._clear();
      this._stopThinking();
      this.talking = false;
      this.queue.length = 0;
      this.play('neutral');                 // calm resting face + blink; mood-driven later
      this.msgEl.classList.remove('typing');
      this.msgEl.textContent = '';          // wipe the old reply FIRST, so it doesn't flash orange
      this.msgEl.classList.add('thinking');
      const text = 'Roll is thinking';        // no trailing dots — they spilled to a second line
      let i = 0, hold = 0;
      this._thinkTimer = setInterval(() => {
        if (hold > 0) { if (--hold === 0) { i = 0; this.msgEl.textContent = ''; } return; }
        this.msgEl.textContent = text.slice(0, ++i);
        if (i >= text.length) hold = 6;       // let the full phrase sit, then clear + retype
      }, 150);                                 // slower, deliberate type-out
    }
    _stopThinking() {
      if (this._thinkTimer) { clearInterval(this._thinkTimer); this._thinkTimer = null; }
      this.msgEl.classList.remove('thinking');
    }

    _startSpeak(state) {
      this._clear();
      this._stopThinking();
      this.talking = true;
      this._voiceSkip = 0; this._moraPos = 0; this._lastVowel = '';   // fresh phrase intonation
      // fires as the line ACTUALLY starts typing (not when it was queued) so a caller can
      // sync UI — e.g. the colored "which tab" header — to the message on screen.
      if (this.onStart) { try { this.onStart(state); } catch (_) {} }
      if (state.clip) this._playClip(state.clip); // her chosen exclamation, at the start of the line

      const baseExpr = NAMES.includes(state.expression) ? state.expression : 'neutral';
      // Untagged lines with a strong base expression still emote the whole way (back-compat); tagged
      // emotion spans override per-segment. Everything else lip-syncs.
      const baseEmote = STRONG_EMOTION[baseExpr] ? baseExpr : null;
      const attrs = parseMarkup(String(state.line));
      const wrapped = this._wrap(attrs.map((c) => c.ch).join(''));   // index-aligned with attrs

      this.msgEl.textContent = '';
      this.msgEl.classList.add('typing');
      let span = null, spanKey = null, emoteNow = ' ';
      let i = 0;

      // Per-character stepper (setTimeout so pacing/pauses can vary the delay): builds styled spans,
      // flips between emote and lip-sync at span boundaries, and drives the mouth on twos.
      const step = () => {
        if (i >= attrs.length) { this._finish(baseExpr); return; }
        const a = attrs[i];
        const ch = wrapped[i] != null ? wrapped[i] : a.ch;

        if (a.sfx) this._playSfx(a.sfx, a.sfxRate);    // explicit [sfx=name(:rate)] reaction

        const emote = a.emote || baseEmote;
        if (emote !== emoteNow) {
          emoteNow = emote;
          span = null;                                   // force a fresh span across an emote boundary
          if (this._emoteHoldTimer) { clearTimeout(this._emoteHoldTimer); this._emoteHoldTimer = null; }
          if (emote) { this._neutralTalk = false; this.play(emote); this._emoteStart = now(); this._playSfx(EMOTE_SFX[emote]); }
          else {
            // Back to neutral talk — but keep the emote face up until MIN_EMOTE_MS has elapsed so a
            // short span is visible. Text keeps typing underneath; only the FACE switch is deferred.
            const toNeutral = () => {
              this._emoteHoldTimer = null;
              this._neutralTalk = true; this._mode = 'talk';
              if (this.animTimer) { clearInterval(this.animTimer); this.animTimer = null; }
              this._frame(MOUTH.closed); this._scheduleBlink();
            };
            const rest = MIN_EMOTE_MS - (now() - (this._emoteStart || 0));
            if (rest > 0) this._emoteHoldTimer = setTimeout(toNeutral, rest);
            else toNeutral();
          }
        }

        const key = (a.b ? 'b' : '') + (a.i ? 'i' : '') + (a.shake ? 's' : '') + (a.wave ? 'w' : '') + (a.color || '');
        if (!span || key !== spanKey) {
          span = document.createElement('span');
          if (a.b) span.style.fontWeight = 'bold';
          if (a.i) span.style.fontStyle = 'italic';
          if (a.color) span.style.color = a.color;
          if (a.shake) span.classList.add('fx-shake');
          if (a.wave) span.classList.add('fx-wave');
          this.msgEl.appendChild(span);
          spanKey = key;
        }
        span.textContent += ch;
        this.msgEl.scrollTop = this.msgEl.scrollHeight;

        if (ch.trim()) {                                              // her voice, per character
          if (this._voiceSkip > 0) this._voiceSkip -= 1;              // already voiced by a multi-char mora
          else this._voiceSkip = this._voiceChar(ch, wrapped.slice(i + 1, i + 3), i) | 0;
        }
        if (this._neutralTalk && i % 2 === 0) this._mouthForChar(ch); // mouth on twos
        if (isSentenceEnd(ch)) this._moraPos = 0;                     // restart the JP pitch downdrift

        i += 1;
        let delay = this._baseDelay() / (a.speed || 1);
        if (a.pause) delay += a.pause;                                // explicit [.] / [p]
        if ('.!?'.includes(ch)) delay += 170;                         // breathe at sentence ends
        else if (',;:'.includes(ch)) delay += 80;
        this.typeTimer = setTimeout(step, delay);
      };
      step();
    }

    _finish(expr) {
      this._clear();
      this.talking = false;
      this.msgEl.classList.remove('typing');
      this.play(STRONG_EMOTION[expr] ? expr : 'neutral');   // strong emotes hold their face; else rest
      if (this.queue.length) {
        // hold the finished line on screen at least half a second, then type the next one
        this.settleTimer = setTimeout(() => { this._startSpeak(this.queue.shift()); }, 500);
      } else {
        this.settleTimer = setTimeout(() => { if (!this.talking) this.play('idle'); }, 2000);
      }
    }
  }

  window.RollFace = RollFace;
})();
